### ISSUE TITLE
Lots of extra spaces.

### ISSUE THREAD

**Issue by PUDGE133** [BuildBoy12/EndConditions#1]
In the created file, wherever there is an entry "- NtfLieutenant", 8 spaces are added at the end.
![Безымянны3й](https://user-images.githubusercontent.com/47304666/91560138-fd4c3f00-e941-11ea-8e67-41c2085a4ba1.png)

**Comment by PUDGE133** [comment]
I also did not quite understand. How can a draw be completely disabled? What happens if I specify only observers in "draw"? If I make everyone observers through the admin panel at the same time, will the round end in a draw?

**Comment by BuildBoy12** [comment]
If you specify spectators in draw, the condition will never succeed since the plugin doesn't count spectators. The spaces shouldnt affect the plugin but I'll see about deleting it. See the other issue for what happens if everyone is forced spectator at the same time.
