### ISSUE TITLE
Alive Class-D & Scientists aren't counted as escaped

### ISSUE THREAD

**Issue by MisterMayoNL** [BuildBoy12/EndConditions#10]
Class-D & Scientists that make it to the end of a round won't count towards the escape conditions like in vanilla SL.

**Example:**
A Class-D is the last remaining person in a match, and no other Class-D's have escaped.
**Vanilla**:
Class-D wins, because even though no Class-D's went through the escape, the winning team has a Class-D that is alive.
**EndConditions**:
Stalemate (using standard rules), because even though there is still a Class-D alive, the Class-D didn't go through the escape.

The end round stats do show alive Class-D & Scientists as escaped/survived, but don't influence the EndCondition rules.

Maybe change the check so that alive Class-D/Scientists count towards the escape conditions?

**Comment by FinnFurwolf** [comment]
I think you can't replicate the vanilla win condition right now, but you can let the plugin block the round, until the Class-D or Scientist escapes and triggers the win. After the first escape, any remaining scientist or Class-D would be ignored, if the corresponding team is alone, so if there are 2 Class-D last alive, only one of them needs to escape.

**Comment by BuildBoy12** [comment]
Should be resolved in 4.0.0-beta.2.
