### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by FinnFurwolf** [BuildBoy12/EndConditions#5]
Would be nice, if you can mark a class as "has to be alive". For example Facility Forces can win, no matter if a scientist escaped, if one is still alive.

**Comment by BuildBoy12** [comment]
You could simply add Scientist to the respective condition, indicating the round will end if any of those classes can be alive for it to end with that condition.

**Comment by FinnFurwolf** [comment]
I am not sure what you mean. If I add Scientist to the MTF Win condition, it would be an MTF Win with for example only one guard left, even if no scientist escaped, if I don't add +science. With +science a scientist has to be escaped for the MTF Win, even if there is one still alive. In the base game the SCPs win, if no one escaped, even if there is a scientist/d-boy still alive. I wanted to change that, but as I understand your plugin, every class in one condition wins together, but not every class in that condition needs to be alive. They CAN win together, but only one of them is needed.

**Comment by BuildBoy12** [comment]
You can make multiple conditions under the same team, if thats what you mean. As an example, having a `+science` condition with only MTF roles and having a condition without `+science` but has the scientist role included with the MTF roles.

**Comment by FinnFurwolf** [comment]
This doesn't work. You can try it yourself. If no scientist escaped and there is only a guard left for example, it will be an MTF win, because all defined classes, that can win together, are optional. The round ends, no matter, if there is a commander, a scientist or a guard alive. Only one of the classes has to be alive. If there is no scientist alive, when no scientist escaped, with only MTF left, I want it to be a Draw instead of a Win.
