### ISSUE TITLE
Round not ending

### ISSUE THREAD

**Issue by FinnFurwolf** [BuildBoy12/EndConditions#6]
I am not sure, if this is caused by your plugin, but I guess it is. I never changed the config since the first time configuring it the way I like and it was fine. After the last EXILED patches something might broke. In some cases, the round will not end, until you manually restart the round, even if nobody is alive. I didn't change any configs. I never saw this before the new EXILED releases (2.1.29/30/31).

**Comment by BuildBoy12** [comment]
Have you attempted disabling this plugin and seeing if the issue persists?

**Comment by FinnFurwolf** [comment]
The problem is, that this is very rare. I couldn't find anything about this issue in the basegame or EXILED bug reports.
I will take a look into the log files, if I can find something.

Edit: Sadly no errors in the log files.

**Comment by FinnFurwolf** [comment]
I disabled the plugin for a while. The issue is gone.

**Comment by BuildBoy12** [comment]
Please see if the issue persists on the latest version of the plugin. I was not able to mimic your behavior during testing.

**Comment by FinnFurwolf** [comment]
Already did that. Same result. Like I said, it is pretty rare. I got it after a few hours, sometimes days.

Edit: I just saw the new releases. I will test it.

**Comment by FinnFurwolf** [comment]
Last update seems to have fixed it. Thank you!
