### ISSUE TITLE
Round end FF

### ISSUE THREAD

**Issue by FinnFurwolf** [BuildBoy12/EndConditions#9]
Enabling round end FF doesn't work anymore.

**Comment by FinnFurwolf** [comment]
This feature works now, but it doesn't get reset after the round restarts, so FF is enabled forever, after the first round ends after a server restart.

**Comment by BuildBoy12** [comment]
Should be resolved in 4.0.0-beta.2.

**Comment by FinnFurwolf** [comment]
FF still gets not reset and stays enabled forever.

**Comment by FinnFurwolf** [comment]
was an EXILED bug
